services:
  pebble:
    image: ghcr.io/letsencrypt/pebble:latest
    command: -config /test/config/pebble-config.json
    ports:
      - 14000:14000 # ACME Directory
      - 15000:15000 # Management Interface (for roots)
    environment:
      - PEBBLE_VA_ALWAYS_VALID=1
      - PEBBLE_VA_NOSLEEP=1
      - PEBBLE_WFE_NONCEREJECT=0

  pebble-challtestsrv:
    image: ghcr.io/letsencrypt/pebble-challtestsrv:latest
    command: -defaultIPv6 ""
    ports:
      - 8055:8055 # HTTP Management

  redis:
    image: redis:latest
    ports:
      - 6379:6379

  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=Password123!
    ports:
      - 1433:1433
